media:
  input: public
  output: /
content:
  - name: editor
    label: Posts
    type: collection
    path: src/content/posts
    view:
      fields: [ title, date, draft ]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: draft, label: Draft, type: boolean, default: true }
      - name: published
        label: Date
        type: date
        options:
          format: yyyy-MM-dd 
        required: true
      - name: category
        label: Category
        type: string
      - name: tags
        label: Tags
        type: string
        list:
          min: 1
          max: 6
      - name: description
        label: Description
        type: string
      - name: image
        label: Cover
        type: image
      - { name: body, label: Text, type: rich-text }