media:
  input: public
  output: /
content:
  - name: editor
    label: Posts
    type: collection
    path: src/content/posts
    view:
      fields: [ title, date, draft ]
    fields:
      - { name: title, label: 标题, type: string, required: true }
      - { name: draft, label: 草稿, type: boolean, default: true }
      - { name: slug, label: 固定链接, type: string, required: true }
      - name: date
        label: 日期
        type: date
        options:
          format: yyyy-MM-dd'T'HH:mm:ss
          time: true
      - name: category
        label: Category
        type: string
      - name: tags
        label: Tags
        type: string
        list:
          min: 1
          max: 6
      - name: imageupload
        label: Upload Images
        type: object
        list: true
        fields:
          - name: addimage
            label: Add Images
            type: image
            options:
              input: public
              output: /
              categories: [image]
      - { name: body, label: 正文, type: rich-text }